Class {
	#name : #Alphabet,
	#superclass : #Object,
	#category : #LanguageDetector
}

{ #category : #'as yet unclassified' }
Alphabet class >> english [

	^ 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
]

{ #category : #'as yet unclassified' }
Alphabet class >> french [

	^ 'AÀÂÆBCÇDEÉÈÊËFGHIÎÏJKLMNOÔŒPQRSTUÙÛÜVWXYŸZaàâæbcçdeéèêëfghiîïjklmnoôœpqrstuùûüvwxyÿz'
]

{ #category : #'as yet unclassified' }
Alphabet class >> spanish [

	^ 'AÁBCDEÉFGHIÍJKLMNÑOÓPQRSTUÚÜVWXYZaábcdeéfghiíjklmnñoópqrstuúüvwxyz'
]
